### ISSUE TITLE
Cache and optimize the meta API call

### ISSUE THREAD

**Issue by espen42** [enonic/nextjs-enonic-demo#41]
Outline / suggestion:
- [ ] Cache the meta API call for content type after the first meta call for a content item.
- [ ] After that, only run the data call for that content item. 
- [ ] Ensure that type is returned with dev-added data queries. 
- [ ] Compare content type returned with data response with cached content type: if not identical, invalidate that cache item, make the meta call again, and re-cache

**Comment by sigdestad** [comment]
Wont fix
