### ISSUE TITLE
0.10.0 release checklist

### ISSUE THREAD

**Issue by sigdestad** [enonic/nextjs-enonic-demo#436]
Code/repo things to solve

- [x] Fix list of release notes (issue flagging)
- [x] Update lib-nextjs for release
- [x] https://github.com/enonic/app-hmdb/issues/40
- [x] Update nextjs-enonic-template (front-end for tutorial)
- [x] Update app-nextjs-demo (back-end of demo)
- [x] Update nextjs-enonic-demo (front-end of demo)
- [x] enonic/cloud-console#1528
- [x] enonic/nextjs-enonic-demo#438

Guide update
- [ ] "TL;DR in guide" must match new setup
- [ ] "Setup Enonic" - Add guillotine during this process
- [ ] "Headless API" - Use new Guillotine approach
- [ ] "Setup next" - env files (env.local?) + mention static vs server rendered
- [ ] "Preview" - New lib, update site.xml (mapping + form + token)
- [ ] "Parts" - discuss getUrl??
- [ ] "Rich text" - Convert bio field in "person" cty?
- [ ] "Production mode" - Move publishing up, new site settings
- [ ] "Deployment" - Update to match new
